name: DevSecOps Pipeline

on: [push, pull_request]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalación de dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Análisis SAST (Semgrep)
        run: |
          pip install semgrep
          semgrep --config=auto --verbose || true

      - name: Análisis SCA (pip-audit)
        run: |
          pip install pip-audit
          pip-audit -r requirements.txt

  dast-scan:
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://practica3-devsecops-miguel-jesus.onrender.com'
          allow_issue_writing: false
          fail_action: false
